version: 0.2

phases:
  install:
    commands:
      - echo "Starting INSTALL phase"
      - echo "Installing NGINX on Amazon Linux"
      - yum clean all
      - yum makecache
      - yum install -y nginx
  build:
    commands:
      - echo "Build started on $(date)"
      - mkdir -p output
      - cp -r * output/
  post_build:
    commands:
      - echo "Build completed successfully on $(date)"
artifacts:
  files:
    - '**/*'
  base-directory: output
