version: 0.2
phases:
  install:
    commands:
      - echo Installing NGINX
      - yum update -y
      - yum install nginx -y
  build:
    commands:
      - echo Building started on '$date'
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX
      
artifacts:
  files: 
   - '**/*'

